
export const stars = [
    { en: 'Ashwini', ml: 'അശ്വതി' },
    { en: 'Bharani', ml: 'ഭരണി' },
    { en: 'Karthika', ml: 'കാർത്തിക' },
    { en: 'Rohini', ml: 'രോഹിണി' },
    { en: 'Makayiram', ml: 'മകയിരം' },
    { en: 'Thiruvathira', ml: 'തിരുവാതിര' },
    { en: 'Punartham', ml: 'പുണർതം' },
    { en: 'Pooyam', ml: 'പൂയം' },
    { en: 'Aayilyam', ml: 'ആയില്യം' },
    { en: 'Makam', ml: 'മകം' },
    { en: 'Pooram', ml: 'പൂരം' },
    { en: 'Uthram', ml: 'ഉത്രം' },
    { en: 'Atham', ml: 'അത്തം' },
    { en: 'Chithira', ml: 'ചിത്തിര' },
    { en: 'Chothi', ml: 'ചോതി' },
    { en: 'Vishakam', ml: 'വിശാഖം' },
    { en: 'Anizham', ml: 'അനിഴം' },
    { en: 'Thrikketta', ml: 'തൃക്കേട്ട' },
    { en: 'Moolam', ml: 'മൂലം' },
    { en: 'Pooradam', ml: 'പൂരാടം' },
    { en: 'Uthradam', ml: 'ഉത്രാടം' },
    { en: 'Thiruvonam', ml: 'തിരുവോണം' },
    { en: 'Avittam', ml: 'അവിട്ടം' },
    { en: 'Chathayam', ml: 'ചതയം' },
    { en: 'Pooruruttathi', ml: 'പൂരുരുട്ടാതി' },
    { en: 'Uthrattathi', ml: 'ഉത്രട്ടാതി' },
    { en: 'Revathi', ml: 'രേവതി' },
];
