// This file is automatically generated. Do not modify it manually.

// Get this from the Firebase console.
export const firebaseConfig = {
  apiKey: "AIzaSyBE1gFXA2b3GW3fYMI3beOxJ2CXuYT_xvY",
  authDomain: "indilayappan-temple.firebaseapp.com",
  projectId: "indilayappan-temple",
  storageBucket: "indilayappan-temple.firebasestorage.app",
  messagingSenderId: "405658738204",
  appId: "1:405658738204:web:2c6291a26b8be26641c9d9"
};