// This file is automatically generated. Do not modify it manually.

// Get this from the Firebase console.
export const firebaseConfig = {
  apiKey: "AIzaSyCyZ8MA7kqpucAYayM0TWKmpQdv1trbDmA",
  authDomain: "industrious-lyceum-2p7vm.firebaseapp.com",
  projectId: "industrious-lyceum-2p7vm",
  storageBucket: "industrious-lyceum-2p7vm.firebasestorage.app",
  messagingSenderId: "533578075028",
  appId: "1:533578075028:web:decc46e025f95f9861dd81",
  firestoreDatabaseId: "ai-studio-indilayappantemp-0e97c30b-b128-46e6-9f46-48aa60e14565"
};
